# https://taskfile.dev

version: "3"

vars:
  BUILD_DIR_BASE: '{{ joinPath .TASKFILE_DIR ".build" }}'
  BUILD_OS: '{{if eq .OS "windows"}}windows{{else}}{{if eq .OS "darwin"}}darwin{{else}}linux{{end}}{{end}}'
  BUILD_DIR: '{{ joinPath .BUILD_DIR_BASE .BUILD_OS }}'
  DEP_SOURCE_DIR: '{{ joinPath .BUILD_DIR "source" }}'
  DEP_BUILD_DIR: '{{ joinPath .BUILD_DIR "out" }}'
  DEP_ARCHIVE_DIR: '{{ joinPath .BUILD_DIR "archives" }}'
  ILOC: '{{ joinPath .BUILD_DIR "install" }}'
  PREFIX_PATH: '{{ .ILOC }}'
  VERSION:
    sh: git describe --tags HEAD

tasks:
  default:
    cmds:
      - task: build

  uri:
    vars:
      URI: '{{ default "https://github.com/zdenop/jbigkit.git" .URI }}'
      GIT_REPO: '{{ .URI | splitList "/" | last }}'
      USERNAME: '{{ .URI | dir | splitList "/" | last }}'
      REPO: '{{ .GIT_REPO | splitList "." | first }}'
    cmds:
      - cmd: 'echo "{{ .GIT_REPO }}"'
      - cmd: 'echo "{{ .USERNAME }}"'
      - cmd: 'echo "{{ .REPO }}"'

  test:
    cmds:
      - cmd: 'echo "{{ .ILOC }}"'
      - cmd: 'echo "{{ .VERSION }}"'

  build:
    name: cmake-win64
    runs-on: windows-latest
    cmds:
      - cmd: scoop install nasm
      - task: task-checkout
      - task: uninstall-perl
      - task: cmake-build-zlib-ng
      - task: cmake-build-libpng
      - task: cmake-build-libjpeg
      - task: cmake-build-jbigkit
      - task: cmake-build-libtiff
      - task: cmake-build-leptonica
      - task: remove-not-needed-tools-before-building-tesseract
      - task: cmake-build-tesseract
      - task: display-tesseract-version-and-test-command-line-usage

  task-checkout:
    cmds:
      - cmd: git submodule update --recursive --checkout --init
      - cmd: git fetch --prune --unshallow --tags
        ignore_error: true
      - cmd: mkdir "{{ fromSlash .ILOC }}"
        ignore_error: true

  uninstall-perl:
    cmds:
      - cmd: choco uninstall strawberryperl
        ignore_error: true

  git-clone:
    required: [URI]
    vars:
      URI: '{{ default "" .URI }}'
      GIT_ARGS: '{{ default "" .GIT_ARGS }}'
      GIT_REPO: '{{ .URI | splitList "/" | last }}'
      USERNAME: '{{ .URI | dir | splitList "/" | last }}'
      REPO_PARSED: '{{ .GIT_REPO | splitList "." | first }}'
      REPO: '{{ coalesce .REPO_PARSED "unknown_repo" }}'
      TARGET_DIR_DEFAULT: '{{ joinPath .DEP_SOURCE_DIR .REPO }}'
      TARGET_DIR: '{{ default .TARGET_DIR_DEFAULT .TARGET_DIR }}'
    preconditions:
      - git --version
    status:
      - test -z "{{ .URI }}" || test -d "{{ .TARGET_DIR }}"
    cmds:
      - cmd: |
          git clone {{ .GIT_ARGS }} --depth 1 "{{ .URI }}" "{{ fromSlash .TARGET_DIR }}"

  git-pull:
    vars:
      TARGET_DIR: '{{ default "" .TARGET_DIR }}'
    preconditions:
      - git --version
    status:
      - test -d "{{ .TARGET_DIR }}"
    cmds:
      - cmd: |
          git -C "{{ fromSlash .TARGET_DIR }}" pull --rebase --recurse-submodules --autostash

  cmake-build:
    vars:
      URI: '{{ default "" .URI }}'
      GIT_REPO: '{{ .URI | splitList "/" | last }}'
      USERNAME: '{{ .URI | dir | splitList "/" | last }}'
      REPO: '{{ .GIT_REPO | splitList "." | first }}'
      TARGET_SOURCE_NAME: '{{ coalesce .TARGET_SOURCE_DIR .TARGET_NAME "" | splitList "/" | last }}'
      TARGET_NAME: '{{ coalesce .TARGET_NAME .TARGET_SOURCE_NAME .REPO }}'
      CONFIG: '{{ default "Release" .CONFIG }}'
      TARGET_SOURCE_DEFAULT_DIR: '{{ joinPath .DEP_SOURCE_DIR .TARGET_NAME }}'
      TARGET_SOURCE_DIR: '{{ default .TARGET_SOURCE_DEFAULT_DIR .TARGET_SOURCE_DIR }}'
      TARGET_BUILD_DIR: '{{ joinPath .DEP_BUILD_DIR .TARGET_NAME }}'
      GIT_ARGS: '{{ default "" .GIT_ARGS }}'
      CONFIGURE_ARGS: '{{ default "" .CONFIGURE_ARGS }}'
      INSTALL_PREFIX: '{{ joinPath .ILOC .TARGET_NAME }}'
    cmds:
      - cmd: |
          echo "Uri: '{{ .URI }}'"
          echo "Git_Repo: '{{ .GIT_REPO }}'"
          echo "Username: '{{ .USERNAME }}'"
          echo "Target_Name: '{{ .TARGET_NAME }}'"
          echo "Target_Source_Dir: '{{ .TARGET_SOURCE_DIR }}'"
          echo "Target_Build_Dir: '{{ .TARGET_BUILD_DIR }}'"
      - task: git-clone
        if: '{{ .URI }} != ""'
        vars: { TARGET_DIR: "{{ .TARGET_SOURCE_DIR }}", URI: "{{ .URI }}", GIT_ARGS: "{{ .GIT_ARGS }}" }
      - cmd: >-
          cmake
          -B "{{ fromSlash .TARGET_BUILD_DIR }}"
          -S "{{ fromSlash .TARGET_SOURCE_DIR }}"
          -DCMAKE_PREFIX_PATH="{{ fromSlash .PREFIX_PATH }}"
          -DCMAKE_INSTALL_PREFIX="{{ fromSlash .INSTALL_PREFIX }}"
          {{ .CONFIGURE_ARGS }}
      - cmd: >-
          cmake
          --build "{{ fromSlash .TARGET_BUILD_DIR }}"
          --config "{{ .CONFIG }}"
          --target install

  cmake-build-zlib-ng:
    cmds:
      - task: cmake-build
        vars:
          URI: https://github.com/zlib-ng/zlib-ng.git
          CONFIGURE_ARGS: >-
            -DBUILD_SHARED_LIBS=OFF
            -DZLIB_COMPAT=ON
            -DZLIB_ENABLE_TESTS=OFF
            -DINSTALL_UTILS=OFF

  clean:
    cmds:
      - cmd: git add .
      - cmd: git clean -xfd
      - cmd: rm -rf "{{ fromSlash .BUILD_DIR_BASE }}"
      - cmd: rm -rf "{{ joinPath .TASKFILE_DIR "zlib-ng" | fromSlash }}"
      - cmd: rm -rf "{{ joinPath .TASKFILE_DIR "libjpeg-turbo" | fromSlash }}"

  deps:
    cmds:
      - task: clean
      - task: cmake-build-libpng
      - task: cmake-build-zlib-ng
      - task: cmake-build-libjpeg
      - task: cmake-build-libtiff

  cmake-build-libpng:
    vars:
      TARGET_NAME: libpng
      FILENAME: lpng1643.zip
      TARGET_SUB_DIRECTORY: '{{ .FILENAME | splitList "." | first }}'
      URI: 'https://download.sourceforge.net/{{ .TARGET_NAME }}/{{ .FILENAME }}'
      OUTPUT_ARCHIVE_FILE_PATH: '{{ joinPath .DEP_ARCHIVE_DIR .FILENAME }}'
      TARGET_SOURCE_DIR_TMP: '{{ joinPath .DEP_BUILD_DIR .TARGET_SUB_DIRECTORY }}'
      TARGET_SOURCE_DIR: '{{ joinPath .DEP_BUILD_DIR .TARGET_NAME }}'
    cmds:
      - cmd: |
          mkdir -p "{{ .OUTPUT_ARCHIVE_FILE_PATH | dir | fromSlash }}"
          curl -sSL -o "{{ fromSlash .OUTPUT_ARCHIVE_FILE_PATH }}" "{{ .URI }}"
      - cmd: |
          mkdir -p "{{ fromSlash .TARGET_SOURCE_DIR_TMP }}"
          unzip -o -qq -d "{{ fromSlash .TARGET_SOURCE_DIR_TMP }}" "{{ fromSlash .OUTPUT_ARCHIVE_FILE_PATH }}"
      - cmd: |
          mkdir -p "{{ fromSlash .TARGET_SOURCE_DIR }}"
          cp -rf "{{ joinPath .TARGET_SOURCE_DIR_TMP .TARGET_SUB_DIRECTORY }}"/* "{{ fromSlash .TARGET_SOURCE_DIR }}"
      - task: cmake-build
        vars:
          TARGET_SOURCE_DIR: '{{ .TARGET_SOURCE_DIR }}'
          CONFIGURE_ARGS: >-
            -DPNG_TESTS=OFF
            -DPNG_SHARED=OFF

  cmake-build-libjpeg:
    cmds:
      - task: cmake-build
        vars:
          TARGET_NAME: libjpeg-turbo
          URI: https://github.com/libjpeg-turbo/libjpeg-turbo.git
          CONFIGURE_ARGS: >-
            -DWITH_TURBOJPEG=OFF
            -DENABLE_SHARED=OFF

  cmake-build-jbigkit:
    cmds:
      - task: cmake-build
        vars:
          TARGET_NAME: jbigkit
          URI: https://github.com/zdenop/jbigkit.git
          CONFIGURE_ARGS: >-
            -DBUILD_PROGRAMS=OFF
            -DBUILD_TOOLS=OFF
            -DCMAKE_WARN_DEPRECATED=OFF

  cmake-build-libtiff:
    cmds:
      - task: cmake-build
        vars:
          TARGET_NAME: libtiff
          URI: https://gitlab.com/libtiff/libtiff.git
          GIT_ARGS: -c advice.detachedHead=false -b "v4.6.0"
          CONFIGURE_ARGS: >-
            -Dtiff-tools=OFF
            -Dtiff-tests=OFF
            -Dtiff-contrib=OFF
            -Dtiff-docs=OFF

  cmake-build-leptonica:
    cmds:
      - task: cmake-build
        vars:
          TARGET_NAME: leptonica
          URI: https://github.com/DanBloomberg/leptonica.git
          CONFIGURE_ARGS: >-
            -DSW_BUILD=OFF
            -DBUILD_PROG=OFF
            -DBUILD_SHARED_LIBS=ON

  remove-not-needed-tools-before-building-tesseract:
    cmds:
      - cmd: rm -Rf "{{ .ILOC }}/bin/"*.exe

  cmake-build-tesseract:
    vars:
      TARGET_NAME: tesseract
      CONFIG: '{{ default "Release" .CONFIG }}'
      TARGET_BUILD_DIR: '{{ joinPath .BUILD_DIR .TARGET_NAME }}'
    cmds:
      - cmd: >-
          cmake
          -B "{{ fromSlash .TARGET_BUILD_DIR }}"
          -S "{{ fromSlash .TASKFILE_DIR }}"
          -DCMAKE_BUILD_TYPE="{{ .CONFIG }}"
          -DCMAKE_PREFIX_PATH="{{ .ILOC }}"
          -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}"
          -DSW_BUILD=OFF
          -DBUILD_SHARED_LIBS=ON
          -DENABLE_LTO=ON
          -DBUILD_TRAINING_TOOLS=OFF
          -DFAST_FLOAT=ON
          -DGRAPHICS_DISABLED=ON
          -DOPENMP_BUILD=OFF
      - cmd: >-
          cmake
          --build "{{ fromSlash .TARGET_BUILD_DIR }}"
          --config "{{ .CONFIG }}"
          --target install

  display-tesseract-version-and-test-command-line-usage:
    cmds:
      - cmd: |
          curl -L https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata --output {{ .ILOC }}/share/tessdata/eng.traineddata
          curl -L https://github.com/tesseract-ocr/tessdata/raw/main/osd.traineddata --output {{ .ILOC }}/share/tessdata/osd.traineddata
          echo "Setting TESSDATA_PREFIX..."
          set TESSDATA_PREFIX={{ .ILOC }}/share/tessdata
          echo "Setting PATH..."
          set PATH={{ .ILOC }}/bin;%PATH%
          echo "Checking installed tesseract version..."
          tesseract -v
          echo "Checking installed langs"
          tesseract --list-langs
          echo "Checking OCR process"
          tesseract test/testing/phototest.tif -
