# https://taskfile.dev

version: "3"

vars:
  ILOC_BASE: '{{ joinPath .TASKFILE_DIR ".local" }}'
  ILOC: "{{ fromSlash .ILOC_BASE }}"
  VERSION:
    sh: git describe --tags HEAD

tasks:
  default:
    cmds:
      - task: build

  test:
    cmds:
      - cmd: 'echo "{{.ILOC}}"'
      - cmd: 'echo "{{.VERSION}}"'

  build:
    name: cmake-win64
    runs-on: windows-latest
    cmds:
      - cmd: scoop install nasm
      - task: task-checkout
      - task: uninstall-perl
      - task: build-and-install-zlib-ng
      - task: build-and-install-libpng
      - task: build-and-install-libjpeg
      - task: build-and-install-jbigkit
      - task: build-and-install-libtiff
      - task: build-and-install-leptonica
      - task: remove-not-needed-tools-before-building-tesseract
      - task: build-and-install-tesseract
      - task: display-tesseract-version-and-test-command-line-usage

  task-checkout:
    cmds:
      - cmd: git submodule update --recursive --checkout --init
      - cmd: git fetch --prune --unshallow --tags
        ignore_error: true
      - cmd: mkdir "{{ .ILOC }}"
        ignore_error: true

  uninstall-perl:
    cmds:
      - cmd: choco uninstall strawberryperl
        ignore_error: true

  build-and-install-zlib-ng:
    cmds:
      - cmd: git clone --depth 1 https://github.com/zlib-ng/zlib-ng.git
        ignore_error: true
      - cmd: git -C zlib-ng pull
        ignore_error: true
      - cmd: |
          cd zlib-ng
          cmake -Bbuild -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -DBUILD_SHARED_LIBS=OFF -DZLIB_COMPAT=ON -DZLIB_ENABLE_TESTS=OFF -DINSTALL_UTILS=OFF
          cmake --build build --config Release --target install

  build-and-install-libpng:
    cmds:
      - cmd: |
          curl -sSL -o lpng1643.zip https://download.sourceforge.net/libpng/lpng1643.zip
          unzip.exe  -qq lpng1643.zip
          cd lpng1643
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -DPNG_TESTS=OFF -DPNG_SHARED=OFF
          cmake --build build --config Release --target install
          cd ..

  build-and-install-libjpeg:
    cmds:
      - cmd: |
          git clone --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo.git
          cd libjpeg-turbo
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -DWITH_TURBOJPEG=OFF -DENABLE_SHARED=OFF
          cmake --build build --config Release --target install
          cd ..

  build-and-install-jbigkit:
    cmds:
      - cmd: |
          git clone --depth 1 https://github.com/zdenop/jbigkit.git
          cd jbigkit
          cmake -Bbuild -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -DBUILD_PROGRAMS=OFF -DBUILD_TOOLS=OFF -DCMAKE_WARN_DEPRECATED=OFF
          cmake --build build --config Release --target install
          cd ..

  build-and-install-libtiff:
    cmds:
      - cmd: |
          git clone -c advice.detachedHead=false -b "v4.6.0" --depth 1 https://gitlab.com/libtiff/libtiff.git
          cd libtiff
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -Dtiff-tools=OFF -Dtiff-tests=OFF -Dtiff-contrib=OFF -Dtiff-docs=OFF
          cmake --build build --config Release --target install
          cd ..

  build-and-install-leptonica:
    cmds:
      - cmd: |
          echo "Building leptonica..."
          git clone --depth 1 https://github.com/DanBloomberg/leptonica.git
          cd leptonica
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -DSW_BUILD=OFF -DBUILD_PROG=OFF -DBUILD_SHARED_LIBS=ON
          cmake --build build --config Release --target install

  remove-not-needed-tools-before-building-tesseract:
    cmds:
      - cmd: rm -Rf {{ .ILOC }}/bin/*.exe

  build-and-install-tesseract:
    cmds:
      - cmd: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="{{ .ILOC }}" -DCMAKE_INSTALL_PREFIX="{{ .ILOC }}" -DSW_BUILD=OFF -DBUILD_SHARED_LIBS=ON -DENABLE_LTO=ON -DBUILD_TRAINING_TOOLS=OFF -DFAST_FLOAT=ON -DGRAPHICS_DISABLED=ON -DOPENMP_BUILD=OFF
          cmake --build build --config Release --target install

  display-tesseract-version-and-test-command-line-usage:
    cmds:
      - cmd: |
          curl -L https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata --output {{ .ILOC }}/share/tessdata/eng.traineddata
          curl -L https://github.com/tesseract-ocr/tessdata/raw/main/osd.traineddata --output {{ .ILOC }}/share/tessdata/osd.traineddata
          echo "Setting TESSDATA_PREFIX..."
          set TESSDATA_PREFIX={{ .ILOC }}/share/tessdata
          echo "Setting PATH..."
          set PATH={{ .ILOC }}/bin;%PATH%
          echo "Checking installed tesseract version..."
          tesseract -v
          echo "Checking installed langs"
          tesseract --list-langs
          echo "Checking OCR process"
          tesseract test/testing/phototest.tif -
