name: vcpkg
# build and test of tesseract on windows using vcpkg and cmake.
# vcpkg with -head does not work. https://github.com/microsoft/vcpkg/issues/16019
on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]
  schedule:
    - cron: 0 23 * * *

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Tesseract Source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install vcpkg
        run: |
          external/vcpkg/bootstrap-vcpkg.bat
          external/vcpkg/vcpkg integrate install

      - name: Configure Tesseract
        run: >-
          cmake .
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DSW_BUILD=OFF
          -DOPENMP_BUILD=OFF
          -DBUILD_TRAINING_TOOLS=OFF
          -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/external/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build Tesseract
        run: |
          cmake --build build --config Release --target install

      - name: Display Tesseract Version
        run: |
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" --version

      - name: Create CMakeLists.txt file for BasicApiTest
        shell: bash
        run: |
          cd test
          cat << "EOF" > CMakeLists.txt
          cmake_minimum_required(VERSION 3.19)
          set(PROJECT_NAME BasicApiTest)
          project( $PROJECT_NAME )
          find_package( Tesseract REQUIRED )
          find_package( Leptonica REQUIRED )
          include_directories(${Tesseract_INCLUDE_DIRS})
          include_directories(${Leptonica_INCLUDE_DIRS})
          add_executable( $PROJECT_NAME testing/basicapitest.cpp )
          target_link_libraries($PROJECT_NAME ${Leptonica_LIBRARIES})
          target_link_libraries($PROJECT_NAME Tesseract::libtesseract)
          add_library(libtesseract UNKNOWN IMPORTED)
          set_property(TARGET libtesseract PROPERTY IMPORTED_LOCATION D:/a/tesseract/tesseract/build/Release/tesseract50.lib)
          target_link_libraries($PROJECT_NAME Tesseract::libtesseract)
          EOF
          cat CMakeLists.txt

      - name: Configure BasicApiTest
        run: |
          cd test
          cmake . "-DCMAKE_TOOLCHAIN_FILE=${env:GITHUB_WORKSPACE}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build BasicApiTest
        run: |
          cd test
          cmake --build .  --config Release

      - name: Download tessdata and image files used for tests
        run: |
          git clone https://github.com/egorpugin/tessdata tessdata_unittest
          mv tessdata_unittest/* ../

      - name: Run BasicApiTest
        run: |
          cd test
          D:\a\tesseract\tesseract\test\Release\BasicApiTest.exe

      - name: Run Tesseract CLI on test images in different languages
        run: |
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" test\testing\phototest.tif - --oem 1  --tessdata-dir ..\tessdata
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" test\testing\raaj.tif - -l hin --oem 1   --tessdata-dir ..\tessdata
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" test\testing\viet.tif - -l vie --oem 1   --tessdata-dir ..\tessdata
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" test\testing\hebrew.png - -l heb --oem 1   --tessdata-dir ..\tessdata
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" test\testing\eurotext.tif - -l fra --oem 1 --tessdata-dir ..\tessdata_best
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" test\testing\arabic.tif - -l ara --oem 1 --psm 6  --tessdata-dir ..\tessdata

      - name: List languages in different test tessdata-dir
        run: |
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" --list-langs --tessdata-dir ..\tessdata
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" --list-langs --tessdata-dir ..\tessdata_best
          "${{ github.workspace }}\build\bin\Release\tesseract.exe" --list-langs --tessdata-dir ..\tessdata_fast
